### ISSUE TITLE
Fire Geolocation at start

### ISSUE THREAD

**Issue by Benjamest** [vUdav/vue2-leaflet-locatecontrol#8]
Hi,

I'm wanting to have the location fire when the map opens. I've had a look through leaflet-locatecontrol and think I need the `.start()` function but I'm not sure how to call it.

Can anyone help?
Thanks

**Comment by Nisgrak** [comment]
You can access the locate control object like this:
```js
this.$refs.locateControlPlugin.mapObject.start();
```

**Comment by dermodmaster** [comment]
> You can access the locate control object like this:
> 
> ```js
> this.$refs.locateControlPlugin.mapObject.start();
> ```

In my case the ref isn't available in mounted scope. You need to wait a bit.
